# to be used in a dev environment only
version: "3.8"
services:
  db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: askit
      POSTGRES_PASSWORD: P@ssw0rd!

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db-data:
