# to be used in a dev environment only
version: "3.8"
services:
  db:
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: askit
      MYSQL_ROOT_PASSWORD: P@ssw0rd!

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db-data:
